// Generated by CoffeeScript 1.6.3
(function() {
  var port;

  port = chrome.runtime.connect({
    name: "lttools"
  });

  window.addEventListener("message", function(event) {
    var action, params, _ref;
    console.log("Message!", event);
    _ref = event.data, action = _ref.action, params = _ref.params;
    if (action === "lttools.watch") {
      console.log("post message!!");
      return port.postMessage({
        data: params
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=lttools.map
*/
